collections:
  projects:
     output: true

defaults:
  - scope:
      path: ""
      type: "my_projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
